require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  IgnoredMethods:
    - describe

RSpec/DescribeClass:
  Exclude:
    - 'spec/config/**/*'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
