require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  IgnoredMethods:
    - describe

RSpec/DescribeClass:
  Exclude:
    - 'spec/config/**/*'
