plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/haml-lint
    - bin/puma
    - bin/rake
    - bin/rspec
    - bin/rubocop
    - bin/thrust
    - vendor/**/*

Metrics/BlockLength:
  AllowedMethods:
    - context
    - describe

RSpec/DescribeClass:
  Exclude:
    - 'spec/config/**/*'

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - 'spec/requests/**/*'

RSpec/NestedGroups:
  Max: 4
