#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler'

$LOAD_PATH.unshift File.join(__dir__, '..', 'lib')
Bundler.require(:default, :development)

require 'application_configuration'
ApplicationConfiguration.load!

require 'dev_training'
@training = DevTraining.new(ENV['console_token']) if ENV['console_token']

$stdout.sync = true
IRB.setup nil
IRB.conf.tap do |c|
  prompt = c[:PROMPT][:DEFAULT].dup
  prompt[:RETURN].prepend '#'

  c[:IRB_NAME] = 'dev-training'
  c[:PROMPT][:CUSTOM] = prompt
  c[:PROMPT_MODE] = :CUSTOM
end

IRB::Irb.new.run(IRB.conf)
