#!/usr/bin/env ruby

# frozen_string_literal: true

require 'fileutils'

# path to your application root.
APP_ROOT = File.expand_path('..', __dir__)

def system!(*args)
  system(*args) || abort("\n== Command #{args} failed ==")
end

FileUtils.chdir APP_ROOT do
  puts '== Installing dependencies =='
  system! 'gem install bundler --conservative'
  system('bundle check') || system!('bundle install')
  system('if command -v rbenv &> /dev/null; then rbenv rehash; fi')
  system 'npm install'

  unless File.exist?('config/application.yml')
    FileUtils.cp 'config/application.yml.example', 'config/application.yml'
  end
end
