name: docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'lib/**/*.rb'
      - 'docs/**/*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/create-github-app-token@v2
        id: docs-github-app-token
        with:
          app-id: ${{ vars.DOCS_APP_ID }}
          private-key: ${{ secrets.DOCS_APP_SECRET_KEY }}
          owner: umts
          repositories: dev-training-web
          permission-contents: write
      - uses: actions/checkout@v5
        with:
          token: ${{ steps.docs-github-app-token.outputs.token }}
      - uses: ./.github/actions/setup
      - run: 'bin/rake rdoc'
      - run: |-
          git config --global user.name 'GitHub Actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add docs/
          git commit -m 'Update documentation [skip ci]' || true
          git push
      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
