on:
  workflow_call:
jobs:
  docker:
    name: app
    uses: umts/shared-workflows/.github/workflows/docker.yml@15c71ed09491317e4eee2a082634b70a245b5651
  haml-lint:
    name: app
    uses: umts/shared-workflows/.github/workflows/haml-lint.yml@15c71ed09491317e4eee2a082634b70a245b5651
  rspec:
    name: app
    uses: umts/shared-workflows/.github/workflows/rspec.yml@15c71ed09491317e4eee2a082634b70a245b5651
    with:
      node: true
      setup_command: "bin/rake test:prepare"
  rubocop:
    name: app
    uses: umts/shared-workflows/.github/workflows/rubocop.yml@15c71ed09491317e4eee2a082634b70a245b5651
  stylelint:
    name: app
    uses: umts/shared-workflows/.github/workflows/stylelint.yml@15c71ed09491317e4eee2a082634b70a245b5651
