on:
  workflow_call:
jobs:
  docker:
    name: app
    uses: umts/.github/.github/workflows/docker.yml@main
  haml-lint:
    name: app
    uses: umts/.github/.github/workflows/haml-lint.yml@main
  rspec:
    name: app
    uses: umts/.github/.github/workflows/rspec.yml@384a4e64b8b22a06e3e237f3d939ffea78321b60
    with:
      node: true
      rack: true
  rubocop:
    name: app
    uses: umts/.github/.github/workflows/rubocop.yml@main
